# Generated by Django 5.1.4 on 2026-06-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='subject',
        ),
    ]
