# Generated by Django 5.1.4 on 2026-06-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('permanent_delete', 'Permanent Delete'), ('snapshot_create', 'Snapshot Create'), ('snapshot_restore', 'Snapshot Restore'), ('settings_change', 'Settings Change'), ('profile_update', 'Profile Update'), ('role_permission_change', 'Role/Permission Change'), ('marks_entry', 'Marks Entry'), ('attendance_entry', 'Attendance Entry'), ('report_card_generation', 'Report Card Generation'), ('payment_create', 'Payment Create'), ('payment_edit', 'Payment Edit'), ('payment_void', 'Payment Void')], db_index=True, max_length=30)),
                ('module', models.CharField(blank=True, db_index=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['module', '-timestamp'], name='audit_audit_module_4e85d9_idx')],
            },
        ),
    ]
