# Generated by Django 5.1.4 on 2026-06-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marks', '0002_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondecision',
            name='decided_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_promotions', to='students.class'),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentranking',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='studentranking',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class'),
        ),
        migrations.AddField(
            model_name='studentranking',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.semester'),
        ),
        migrations.AddField(
            model_name='studentranking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='conductrating',
            unique_together={('student', 'category', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='gradingscale',
            unique_together={('academic_year', 'grade_letter')},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='promotiondecision',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentranking',
            unique_together={('student', 'academic_year', 'semester')},
        ),
    ]
