# Generated by Django 5.1.4 on 2026-06-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.guardian'),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='students.StudentGuardian', to='students.guardian'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'section', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentguardian',
            unique_together={('student', 'guardian')},
        ),
    ]
